# frozen_string_literal: true

default['magento']['date'] = Time.new
default['magento']['csf']['TESTING'] = '"1"'
default['magento']['csf']['RESTRICT_SYSLOG'] = '"3"'
default['magento']['csf']['LF_POP3D'] = '"10"'
default['magento']['csf']['LF_IMAPD'] = '"10"'
default['magento']['csf']['LF_IMAPD'] = '"10"'
default['magento']['csf']['SYSLOG_CHECK'] = '"3600"'
default['magento']['csf']['TCP_IN'] = '"22,80,443,19999"'
default['magento']['csf']['UDP_IN'] = '"53"'
default['magento']['csf']['TCP6_IN'] = '"80,443,19999"'
default['magento']['csf']['UDP6_IN'] = '"53"'

# my.cnf
default['magento']['mysql']['datadir'] = '/var/lib/mysql'
default['magento']['mysql']['socket'] = '/var/lib/mysql/mysql.sock'
default['magento']['mysql']['log-error'] = '/var/log/mariadb/mariadb_error.log'
default['magento']['mysql']['symbolic-links'] = '0'
default['magento']['mysql']['max_connections'] = '700'
default['magento']['mysql']['join_buffer_size'] = '10M'
default['magento']['mysql']['performance_schema'] = 'on'
default['magento']['mysql']['slow-query-log'] = '1'
default['magento']['mysql']['slow-query-log-file'] = '/var/lib/mysql/mysql-slow.log'
default['magento']['mysql']['long_query_time'] = '1'
default['magento']['mysql']['query_cache_size'] = '128M'
default['magento']['mysql']['query_cache_limit'] = '128M'
default['magento']['mysql']['query_cache_type'] = '1'
default['magento']['mysql']['thread_cache_size'] = '8'
default['magento']['mysql']['myisam_sort_buffer_size'] = '64M'
default['magento']['mysql']['read_rnd_buffer_size'] = '8M'
default['magento']['mysql']['read_buffer_size'] = '2M'
default['magento']['mysql']['sort_buffer_size'] = '2M'
default['magento']['mysql']['table_open_cache'] = '1024'
default['magento']['mysql']['max_allowed_packet'] = '32M'
default['magento']['mysql']['key_buffer_size'] = '384M'
default['magento']['mysql']['tmp_table_size'] = '2G'
default['magento']['mysql']['max_heap_table_size'] = '512M'
default['magento']['mysql']['innodb_file_per_table'] = '2'
default['magento']['mysql']['innodb_log_file_size'] = '2G'
default['magento']['mysql']['innodb_buffer_pool_instances'] = '1'
default['magento']['mysql']['innodb-ft-min-token-size'] = '2'
default['magento']['mysql']['innodb_ft_enable_stopword'] = '""'
default['magento']['mysql']['ft_min_word_len'] = '1'
default['magento']['mysql']['ft_stopword_file'] = '""'
# default['magento']['mysql']['innodb_buffer_pool_size'] = ((1024 + (256 * Math.log(19, 2)) * 2) ).
p_mem = node['memory']['total']
men = p_mem[0...-2].to_i / 1024
t_mem = men
default['magento']['mysql']['innodb_buffer_pool_size'] = ((t_mem * 1024 - 2 * (256 + 256 * Math.log2(t_mem)).to_i) / (1.05 * 1024)).to_i
# if(ramValue <= 1) { result = 128; display = result + ' MB'; } else if(ramValue < 32) { var OS= Math.round(256+256*(Math.log2(ramValue))); result = (ramValue*1024-2*OS)/(1.05*1024); if(result < 2) { display = result.toFixed(2) + ' GB'; } else { display = Math.round(result) + ' GB'; } } else { var OS = Math.round(0.05*ramValue*1024); result = (ramValue*1024-2*OS)/(1.05*1024); display = Math.round(result) + ' GB'; }

# php.ini
default['magento']['php']['short_open_tag'] = 'On'
default['magento']['php']['memory_limit'] = '1024M'
default['magento']['php']['post_max_size'] = '128M'
default['magento']['php']['upload_max_filesize'] = '64M'
# default['magento']['php']['disable_functions'] = 'exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source'
default['magento']['php']['disable_functions'] = '""'

# nginx.conf

default['magento']['nginx']['user'] = 'nginx'
default['magento']['nginx']['worker_processes'] = 'auto'
default['magento']['nginx']['error_log'] = '/var/log/nginx/error.log'
default['magento']['nginx']['error_log_type'] = 'warn'
default['magento']['nginx']['worker_connections'] = '2048'
default['magento']['nginx']['access_log'] = '/var/log/nginx/access.log'
default['magento']['nginx']['sendfile'] = 'on'
default['magento']['nginx']['log_subrequest'] = 'on'
default['magento']['nginx']['tcp_nopush'] = 'on'
default['magento']['nginx']['tcp_nodelay'] = 'on'
default['magento']['nginx']['etag'] = 'on'
default['magento']['nginx']['keepalive_timeout'] = '75'
default['magento']['nginx']['types_hash_max_size'] = '2048'
default['magento']['nginx']['resolver'] = '1.1.1.1 valid=30s'
default['magento']['nginx']['gzip'] = 'on'
default['magento']['nginx']['gzip_comp_level'] = '6'
default['magento']['nginx']['gzip_min_length'] = '100'
default['magento']['nginx']['gzip_http_version'] = '1.1'
default['magento']['nginx']['gzip_vary'] = 'on'
default['magento']['nginx']['gzip_proxied'] = 'any'
default['magento']['nginx']['gzip_types'] = 'text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml application/x-font-ttf font/opentype image/jpeg image/png'
default['magento']['nginx']['gzip_static'] = 'always'
default['magento']['nginx']['gzip_buffers'] = '16 8k'
default['magento']['nginx']['gzip_disable'] = '“MSIE [1-6].(?!.*SV1)”'
default['magento']['nginx']['server_tokens'] = 'off'
default['magento']['nginx']['fastcgi_read_timeout'] = '600'
default['magento']['nginx']['server_names_hash_bucket_size'] = '128'
default['magento']['nginx']['cloudflare_ips'] = '/etc/nginx/cloudflare.conf'
